-- TechNova gamification schema.
-- PREPARED ONLY: do not run automatically.
-- This file is intentionally not applied from ChatGPT because database changes require explicit approval.

create table if not exists public.achievements (
  key text primary key,
  title text not null,
  description text not null,
  icon text not null default '🏆',
  xp integer not null default 0 check (xp >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.user_xp (
  user_id uuid primary key references auth.users(id) on delete cascade,
  xp integer not null default 0 check (xp >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null references public.achievements(key) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_key)
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null,
  explanation text,
  points integer not null default 10 check (points >= 0),
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null default 0 check (score >= 0),
  total_questions integer not null default 0 check (total_questions >= 0),
  completed_at timestamptz not null default now()
);

alter table public.achievements enable row level security;
alter table public.user_xp enable row level security;
alter table public.user_achievements enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;

-- Public catalog; writes should be performed by trusted admin code.
drop policy if exists "achievements_select_authenticated" on public.achievements;
create policy "achievements_select_authenticated"
on public.achievements for select
to authenticated using (true);

-- Users can read their own score. Admin policies should use the existing private.is_admin() helper.
drop policy if exists "user_xp_select_own" on public.user_xp;
create policy "user_xp_select_own"
on public.user_xp for select
to authenticated using (auth.uid() = user_id);

drop policy if exists "user_xp_select_admin" on public.user_xp;
create policy "user_xp_select_admin"
on public.user_xp for select
to authenticated using (private.is_admin());

drop policy if exists "user_achievements_select_own" on public.user_achievements;
create policy "user_achievements_select_own"
on public.user_achievements for select
to authenticated using (auth.uid() = user_id);

drop policy if exists "user_achievements_select_admin" on public.user_achievements;
create policy "user_achievements_select_admin"
on public.user_achievements for select
to authenticated using (private.is_admin());

-- Quiz catalogue is readable to signed-in users; attempts are private to their owner plus admins.
drop policy if exists "quiz_questions_select_authenticated" on public.quiz_questions;
create policy "quiz_questions_select_authenticated"
on public.quiz_questions for select
to authenticated using (published = true or private.is_admin());

drop policy if exists "quiz_attempts_select_own" on public.quiz_attempts;
create policy "quiz_attempts_select_own"
on public.quiz_attempts for select
to authenticated using (auth.uid() = user_id);

drop policy if exists "quiz_attempts_select_admin" on public.quiz_attempts;
create policy "quiz_attempts_select_admin"
on public.quiz_attempts for select
to authenticated using (private.is_admin());

drop policy if exists "quiz_attempts_insert_own" on public.quiz_attempts;
create policy "quiz_attempts_insert_own"
on public.quiz_attempts for insert
to authenticated with check (auth.uid() = user_id);

insert into public.achievements (key,title,description,icon,xp) values
('first-login','Welcome to TechNova','Create your TechNova profile.','👋',25),
('first-event','Event Explorer','Register for your first event.','🎟️',50),
('saved-event','Plan Ahead','Save an event for later.','❤️',25),
('first-comment','Community Voice','Leave your first approved comment.','💬',50),
('first-article','Tech Reader','Read your first technology article.','📰',25),
('ai-chat','AI Curious','Ask TechNova AI your first question.','🤖',50),
('five-events','Event Regular','Register for five events.','🏆',150),
('ten-events','TechNova Veteran','Register for ten events.','🚀',300)
on conflict (key) do update set title=excluded.title,description=excluded.description,icon=excluded.icon,xp=excluded.xp;
